#!/usr/bin/env python3
"""Generate crates/lumen/src/cldr_units.rs from CLDR unit display patterns.

Source: unicode-org/cldr-json, package `cldr-units-full` (CLDR 48.2.0).
For each locale we read `<loc>/units.json` and emit the `unitPattern-count-{one,other}`
strings for the ECMA-402 sanctioned single units, across the long/short/narrow styles.

The CLDR key for a sanctioned unit is category-prefixed (e.g. `duration-second`,
`length-centimeter`). The sanctioned id is the key with its leading category segment
removed, so we resolve each unit by matching `key.split('-', 1)[1] == unit` — matching
by bare suffix instead is what corrupted the previous table (`second` picking up
`acceleration-meter-per-square-second`, `centimeter` picking up `area-square-centimeter`).

Usage:
    python3 scripts/gen-cldr-units.py            # fetch from CDN, write the .rs file
    CLDR_DIR=/path/to/json python3 scripts/...   # read pre-downloaded <loc>.json files
"""

import json
import os
import sys
import urllib.request

CLDR_PACKAGE_VERSION = "48.2.0"
BASE_URL = (
    "https://raw.githubusercontent.com/unicode-org/cldr-json/main/"
    "cldr-json/cldr-units-full/main"
)

# Locales carried by the engine, in table order.
LOCALES = [
    "en", "en-IN", "de", "fr", "es", "it", "pt", "nl",
    "ja", "ko", "zh-Hant", "zh-Hans", "ru", "ar", "pl",
]

STYLES = ["long", "short", "narrow"]
COUNTS = ["one", "other"]

# ECMA-402 sanctioned single units, in table order (simple units alphabetical, the two
# compound speed units appended last).
UNITS = [
    "acre", "bit", "byte", "celsius", "centimeter", "day", "degree", "fahrenheit",
    "fluid-ounce", "foot", "gallon", "gigabit", "gigabyte", "gram", "hectare", "hour",
    "inch", "kilobit", "kilobyte", "kilogram", "kilometer", "liter", "megabit",
    "megabyte", "meter", "microsecond", "mile", "mile-scandinavian", "milliliter",
    "millimeter", "millisecond", "minute", "month", "nanosecond", "ounce", "percent",
    "petabyte", "pound", "second", "stone", "terabit", "terabyte", "week", "yard",
    "year", "kilometer-per-hour", "meter-per-second",
]


def load_locale(loc):
    cldr_dir = os.environ.get("CLDR_DIR")
    if cldr_dir:
        with open(os.path.join(cldr_dir, f"{loc}.json")) as f:
            data = json.load(f)
    else:
        with urllib.request.urlopen(f"{BASE_URL}/{loc}/units.json", timeout=60) as r:
            data = json.load(r)
    return data["main"][loc]["units"]


def resolve_keys(long_section):
    """Map each sanctioned unit id to its category-prefixed CLDR key."""
    candidates = [k for k in long_section if "-" in k and not k[0].isdigit()]
    mapping = {}
    for unit in UNITS:
        matches = [k for k in candidates if k.split("-", 1)[1] == unit]
        if len(matches) != 1:
            raise SystemExit(f"unit {unit!r} resolved to {matches!r}, expected exactly one")
        mapping[unit] = matches[0]
    return mapping


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    rows = []
    for loc in LOCALES:
        units = load_locale(loc)
        keys = resolve_keys(units["long"])
        for style in STYLES:
            section = units[style]
            for unit in UNITS:
                entry = section.get(keys[unit])
                if not entry:
                    continue
                for count in COUNTS:
                    pat = entry.get(f"unitPattern-count-{count}")
                    if pat is None:
                        continue
                    rows.append((loc, unit, style, count, pat))

    out = [
        "//! CLDR unit display patterns, generated by scripts/gen-cldr-units.py. DO NOT EDIT.",
        "//! `{0}` is the number placeholder.",
        "",
        "#[rustfmt::skip]",
        f"static UNIT_PATTERNS: [(&str, &str, &str, &str, &str); {len(rows)}] = [",
    ]
    for loc, unit, style, count, pat in rows:
        out.append(f'    ("{loc}", "{unit}", "{style}", "{count}", "{esc(pat)}"),')
    out += [
        "];",
        "",
        "/// The unit display pattern for a CLDR locale key, unit, style and plural category.",
        "pub fn unit_pattern(loc: &str, unit: &str, style: &str, plural: &str) -> Option<&'static str> {",
        "    UNIT_PATTERNS",
        "        .iter()",
        "        .find(|(l, u, s, p, _)| *l == loc && *u == unit && *s == style && *p == plural)",
        "        .map(|(_, _, _, _, pat)| *pat)",
        "}",
        "",
    ]

    dest = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "crates", "lumen", "src", "cldr_units.rs",
    )
    with open(dest, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {len(rows)} rows to {dest}", file=sys.stderr)


if __name__ == "__main__":
    main()
